//Artist actions types
export const REQUEST_ALL_ARTISTS = "REQUEST_ALL_ARTISTS";
export const REQUEST_ALL_ARTISTS_DONE = "REQUEST_ALL_ARTISTS_DONE";
export const ARTIST_GET_ALL_TRACKS = "ARTIST_GET_ALL_TRACKS";
export const ARTIST_GET_ALL_TRACKS_DONE = "ARTIST_GET_ALL_TRACKS_DONE";

//Playlist actions types

export const ADD_TRACK_TO_PLAYLIST="ADD_TRACK_TO_PLAYLIST";
export const REMOVE_TRACK_FROM_PLAYLIST= "REMOVE_TRACK_FROM_PLAYLIST";